name: Build APK and Notify Discord

on:
  push:
    branches:
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Android SDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Get latest commit message and ID
        id: get_commit_info
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Discord notification
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
  uses: Ilshidur/action-discord@0.3.2
  with:
    args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
