name: Build APK and Notify Discord

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

      
    - name: Get latest commit message and ID
      id: get_commit_info
      run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "COMMIT_ID=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
          name: Dantotsu
          path: "app/build/outputs/apk/debug/app-debug.apk"   
          
    - name: Upload APK to Discord
      shell: bash
      run: |
        contentbody=$( jq -Rsa . <<< "${{ github.event.head_commit.message }}" )
        curl -F "payload_json={\"content\":\"everyone **${{ env.VERSION }}**\n\n${contentbody:1:-1}\"}" -F "dantotsu_debug=@app/build/outputs/apk/debug/app-debug.apk" ${{ secrets.DISCORD_WEBHOOK }}

